version: "3.7"

services:
  xds:
    image: vmagentacr.azurecr.io/mdc/xds:latest 
    command: /xds /conf/xds_conf.yaml
    network_mode: "host"
    expose:
      - "12345"
    volumes:
      - ./xds:/conf
  envoy:
    image: envoyproxy/envoy:v1.16.1
    command: bash /app/start.sh 2
    network_mode: "host"
    environment:
    - MIR_MESH_DISABLE=false 
    - MIR_ENVOY_RETRY_ATTEMPTS=10 
    - MIR_SCORING_PROXY_MAX_CONNECTION_DURATION=240 
    - ENABLE_TRITON_MULTI_MODEL=false 
    - ENVOY_MESH_LOAD_BALANCE_ALGO=ROUND_ROBIN 
    - HOST_IP=xds 
    - MIR_MODEL_USE_HTTP2=false 
    - MIR_ENVOY_HIGH_QPS_OPTIMIZED=true 
    - MIR_ENABLE_MESH_HTTP2=false 
    - MODEL_REQUEST_TIMEOUT=600 
    - ENABLE_MDC=true 
    - MIR_MTLS_DISABLE=false 
    - MIR_ENVOY_LOG_LEVEL=warn 
    - MIR_SCORING_PROXY_IDLE_TIMEOUT=60
    volumes:
      - ./envoy:/app
  envoy_wo_mdc:
    image: envoyproxy/envoy:v1.16.1
    command: bash /app/start.sh 2
    network_mode: "host"
    environment:
    - MIR_MESH_DISABLE=false 
    - MIR_ENVOY_RETRY_ATTEMPTS=10 
    - MIR_SCORING_PROXY_MAX_CONNECTION_DURATION=240 
    - ENABLE_TRITON_MULTI_MODEL=false 
    - ENVOY_MESH_LOAD_BALANCE_ALGO=ROUND_ROBIN 
    - HOST_IP=xds 
    - MIR_MODEL_USE_HTTP2=false 
    - MIR_ENVOY_HIGH_QPS_OPTIMIZED=true 
    - MIR_ENABLE_MESH_HTTP2=false 
    - MODEL_REQUEST_TIMEOUT=600 
    - ENABLE_MDC=false 
    - MIR_MTLS_DISABLE=false 
    - MIR_ENVOY_LOG_LEVEL=warn 
    - MIR_SCORING_PROXY_IDLE_TIMEOUT=60
    volumes:
      - ./envoy_wo_mdc:/app
  mdc:
    image: vmagentacr.azurecr.io/public/mir/mir-mdc:latest
    entrypoint: ./app/mdc-server
    command: -config /conf/config.json -http :50011 -log-level debug
    network_mode: "host"
    volumes:
      - ./mdc:/conf
    environment:
      - eventhubConnStr=${eventhubConnStr}
      - blobKey=${blobKey}
      - blobName=${blobName}
  model:
    image: syntest:latest
    network_mode: "host"
    environment:
        - HTTP_PORT=5001
    