# The base go-image
FROM golang:1.15-alpine
 
# Create a directory for the app
RUN mkdir /app
 
WORKDIR /app

COPY go.mod /app/go.mod
COPY go.sum /app/go.sum

RUN go mod download

COPY cmds/client/client.go /app/client.go
 
# Set working directory
 
# Run command as described:
# go build will build an executable file named server in the current directory
RUN go build -o client . 
 

RUN mkdir /work
WORKDIR /work

# Run the server executable
CMD [ "/app/client" ]